all:PyMod.c
	gcc -shared -o PyMod.so PyMod.c -fPIC
clean:
	rm -f PyMod.so
#	gcc -c PyMod.c -I/Python27/include -fPIC
#	gcc -shared PyMod.o -L/home/shawn/.pyenv/versions/2.7.8/lib -lpython27 -o PyMod.so
